;;; php-cs-fixer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from php-cs-fixer.el

(let ((loads (get 'php-cs-fixer 'custom-loads))) (if (member '"php-cs-fixer" loads) nil (put 'php-cs-fixer 'custom-loads (cons '"php-cs-fixer" loads)) (put 'languages 'custom-loads (cons 'php-cs-fixer (get 'languages 'custom-loads)))))
(autoload 'php-cs-fixer-fix "php-cs-fixer" "\
Formats the current PHP buffer according to the PHP-CS-Fixer tool." t)
(autoload 'php-cs-fixer-before-save "php-cs-fixer" "\
Used to automatically fix the file saving the buffer.
Add this to .emacs to run php-cs-fix on the current buffer when saving:
 (add-hook \\='before-save-hook \\='php-cs-fixer-before-save)." t)
(register-definition-prefixes "php-cs-fixer" '("php-cs-fixer-"))

;;; End of scraped data

(provide 'php-cs-fixer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; php-cs-fixer-autoloads.el ends here
