;;; flycheck-css-colorguard-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-css-colorguard.el

(autoload 'flycheck-css-colorguard-setup "flycheck-css-colorguard" "\
Setup Flycheck CSS Colorguard.
Add `css-colorguard' to `flycheck-checkers'." t)

;;; End of scraped data

(provide 'flycheck-css-colorguard-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-css-colorguard-autoloads.el ends here
