;;; ox-qmd-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ox-qmd.el

(autoload 'org-qmd-export-as-markdown "ox-qmd" "\
Export current buffer to a Qiita Markdown buffer.

If narrowing is active in the current buffer, only export
its narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should
happen asynchronously.  The resulting buffer should be
accessible through the `org-export-stack' interface.

When optional argument SUBTREEP is non-nil, export the
sub-tree at point, extracting information from the headline
properties first.

When optional argument VISIBLE-ONLY is non-nil, don't export
contents of hidden elements.

Export is done in a buffer named \"*Org QMD Export*\", which
will be displayed when
`org-export-show-temporary-export-buffer' is non-nil.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY)" t)
(autoload 'org-qmd-convert-region-to-md "ox-qmd" "\
Convert region into Qiita Markdown format.
Assume the current region has org mode syntax,  and convert
it to Qiita Markdown.  This can be used in any buffer.  For
example, you can write an itemized list in org mode syntax
in a Markdown buffer and use this command to convert it." t)
(autoload 'org-qmd-export-to-markdown "ox-qmd" "\
Export current buffer to a Qiita Markdown file.

If narrowing is active in the current buffer, only export
its narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should
happen asynchronously.  The resulting file should be
accessible through the `org-export-stack' interface.

When optional argument SUBTREEP is non-nil, export the
sub-tree at point, extracting information from the headline
properties first.

When optional argument VISIBLE-ONLY is non-nil, don't export
contents of hidden elements.

Return output file's name.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY)" t)
(register-definition-prefixes "ox-qmd" '("org-qmd--" "ox-qmd-"))


;;; Generated autoloads from ox-qmd-upload-inline-image.el

(register-definition-prefixes "ox-qmd-upload-inline-image" '("org-qmd--link-suppoting-image-upload" "ox-qmd--upload-inline-image"))

;;; End of scraped data

(provide 'ox-qmd-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ox-qmd-autoloads.el ends here
